### ISSUE TITLE
Could it work for architecture arm64?

### ISSUE THREAD

**Issue by nyxophyl** [lutin11/mattermost_dc#2]
Hello,
I would like to run the software on a oneplus 3t which is arm64. So I built the project using arm64 and installed the app on the phone. Unfortunately, the app does not run. No logfile of the app is created. In the unity8.log it is just seen, that the app starts and then stops immediately without a hint why.
Is there a reason, why the app is only available for architecture armhf? Do I have a chance to get it runnable on arm64?

**Comment by lutin11** [comment]
Hello,
This app, is really outdated. I haven't got much time to maintain it. It
uses oxide lib that should be replaced.
I would not advise to use it.
Sorry

**Comment by nyxophyl** [comment]
Thanks to let me know.
